name: Heisman Winner
description: Record a Heisman winner
title: "[Heisman] Player (Year)"
labels: ["submission","heisman"]
body:
  - type: input
    id: year
    attributes: { label: Year, placeholder: "2025" }
    validations: { required: true }

  - type: input
    id: player
    attributes: { label: Player, placeholder: "QB John Example" }
    validations: { required: true }

  - type: input
    id: school
    attributes: { label: School, placeholder: "Oregon" }
    validations: { required: true }
