name: National Champion
description: Submit a national champion
labels: ["submission","natty"]
title: "[Natty] Team (Year)"
body:
  - type: input
    id: year
    attributes: { label: Year, placeholder: "2025" }
    validations: { required: true }

  - type: input
    id: team
    attributes: { label: Champion Team, placeholder: "Texas A&M" }
    validations: { required: true }

  - type: input
    id: coach
    attributes: { label: Coach, placeholder: "Cameron" }
    validations: { required: true }

  - type: input
    id: record
    attributes: { label: Record, placeholder: "14-1" }
